const pokeneas = [
    {id: "1", name: "Espeon", height: "0,9 m", ability:"Sincronia", image: "https://storage.googleapis.com/taller-2-bucket/196.png", philosophical_phrase: "Al predecir el siguiente movimiento de su rival, los extremos de su cola bifida tiemblan ligeramente."},
    {id: "2", name: "Giratina", height: "4,5 m", ability:"", image:'https://storage.googleapis.com/taller-2-bucket/487.png', philosophical_phrase: "Vive en el Mundo Distorsion, un mundo opuesto al nuestro y cuyas leyes desafian el sentido comun."},
    {id: "3", name: "Darkrai", height: "1,5 m", ability:"Mal Sueño", image:'https://storage.googleapis.com/taller-2-bucket/491.png', philosophical_phrase: "Defiende su territorio de personas y Pokemon haciendoles dormir y provocandoles pesadillas."},
    {id: "4", name: "Gothitelle", height: "1,5 m", ability:"Cacheo", image:'https://storage.googleapis.com/taller-2-bucket/576.png', philosophical_phrase: "Libera su poder psiquico e induce al rival a soñar con el fin del universo, un espectaculo al parecer tan bello como efimero."},
    {id: "5", name: "Florges", height: "1,1 m", ability:"Velo Flor", image:'https://storage.googleapis.com/taller-2-bucket/671.png', philosophical_phrase: "Hace de su territorio un jardin esplendoroso. Extrae su poder de las flores rojas que lleva en torno al cuello."},
    {id: "6", name: "Sylveon", height: "1,0 m", ability:"Gran Encanto", image:'https://storage.googleapis.com/taller-2-bucket/700.png', philosophical_phrase: "Con sus apendices sensoriales con forma de cinta, emite unas ondas tranquilizadoras capaces de neutralizar la hostilidad de sus rivales."},
    {id: "7", name: "Xerneas", height: "3,0 m", ability:"Aura Feerica", image:'https://storage.googleapis.com/taller-2-bucket/716.png', philosophical_phrase: "Segun las leyendas, puede compartir el secreto de la vida eterna. Ha despertado tras dormir durante mil años bajo la apariencia de un arbol."},
    {id: "8", name: "Mimikyu", height: "0,2 m", ability:"Disfraz", image:'https://storage.googleapis.com/taller-2-bucket/778.png', philosophical_phrase: "Vive en lugares oscuros donde no llega el sol. Cuando se deja ver por la gente, oculta todo su cuerpo bajo un saco con aspecto de Pikachu."},
    {id: "9", name: "Spectrier", height: "2,0 m", ability:"Relincho Negro", image:'https://storage.googleapis.com/taller-2-bucket/897.png', philosophical_phrase: "Examina su entorno con todos los sentidos, salvo la vista. Se dice que sus coces son capaces de robarle el alma a quien las recibe."},   
    {id: "10", name: "Wyrdeer", height: "1,8 m", ability:"Intimidacion", image:'https://storage.googleapis.com/taller-2-bucket/899.png', philosophical_phrase: "Sus orbes negros brillan con un fulgor misterioso cuando erige muros invisibles. El pelaje que se desprende de sus barbas es muy codiciado para crear calidos ropajes para el invierno."},
];

module.exports = pokeneas;